-- ============================================================
-- Challenge Motiva - Sprint 3
-- Script de dados de teste (Oracle)
-- Execute DEPOIS do seu-script-criacao.sql
-- ============================================================

-- Equipes (ID e gerado automaticamente pela IDENTITY)
INSERT INTO EQUIPE_MANUTENCAO (NOME, QUANTIDADE_MEMBROS, TIPO, TIPO_EQUIPAMENTO)
    VALUES ('Equipe Alfa', 5, 'ROCADA', 'Trator de arrasto');
INSERT INTO EQUIPE_MANUTENCAO (NOME, QUANTIDADE_MEMBROS, TIPO, TIPO_EQUIPAMENTO)
    VALUES ('Equipe Beta', 3, 'MANUTENCAO', NULL);
INSERT INTO EQUIPE_MANUTENCAO (NOME, QUANTIDADE_MEMBROS, TIPO, TIPO_EQUIPAMENTO)
    VALUES ('Equipe Gama', 4, 'ROCADA', 'Rocadeira costal');

-- Trechos (a FK usa subconsulta pelo nome da equipe, evitando "chutar" o ID)
INSERT INTO TRECHO_RODOVIA (IDENTIFICACAO, QUILOMETRO_INICIAL, QUILOMETRO_FINAL, NIVEL_VEGETACAO, TIPO, EQUIPE_ID)
    VALUES ('BR-116 KM 10 ao 15', 10.0, 15.0, 62.0, 'UMIDO',
            (SELECT ID FROM EQUIPE_MANUTENCAO WHERE NOME = 'Equipe Alfa'));
INSERT INTO TRECHO_RODOVIA (IDENTIFICACAO, QUILOMETRO_INICIAL, QUILOMETRO_FINAL, NIVEL_VEGETACAO, TIPO, EQUIPE_ID)
    VALUES ('SP-348 KM 50 ao 60', 50.0, 60.0, 18.0, 'SECO',
            (SELECT ID FROM EQUIPE_MANUTENCAO WHERE NOME = 'Equipe Beta'));
INSERT INTO TRECHO_RODOVIA (IDENTIFICACAO, QUILOMETRO_INICIAL, QUILOMETRO_FINAL, NIVEL_VEGETACAO, TIPO, EQUIPE_ID)
    VALUES ('BR-101 KM 200 ao 210', 200.0, 210.0, 40.0, 'COMUM', NULL);
INSERT INTO TRECHO_RODOVIA (IDENTIFICACAO, QUILOMETRO_INICIAL, QUILOMETRO_FINAL, NIVEL_VEGETACAO, TIPO, EQUIPE_ID)
    VALUES ('SP-021 KM 5 ao 12', 5.0, 12.0, 75.0, 'UMIDO',
            (SELECT ID FROM EQUIPE_MANUTENCAO WHERE NOME = 'Equipe Gama'));

-- Intervencoes
INSERT INTO INTERVENCAO_OPERACIONAL (TIPO, RESPONSAVEL)
    VALUES ('MECANIZADA', 'Equipe Alfa');
INSERT INTO INTERVENCAO_OPERACIONAL (TIPO, RESPONSAVEL)
    VALUES ('PULVERIZACAO', 'Equipe Beta');

COMMIT;
